# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IEEE MNNIT
email: ieeemnnit@mnnit.ac.in

description: >- # this means to ignore newlines until "baseurl:"
  Student Branch Code: STB08071. School Code: A28995. The Institute of Electrical and Electronics Engineers Inc. (IEEE) was founded in 1884 with a mission to foster technological innovation and excellence for the benefit of humanity. 
baseurl: "/ieeemnnit" # the subpath of your site, e.g. /blog
url: "https://mgeekin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: prateekrgautam
github_username:  prateekrajgautam

# Build settings
markdown: kramdown
theme: ieee-students-branch-jekyll-theme
remote_theme: mgeekin/ieee-students-branch-jekyll-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
permalink: /:path/:title/

assets: https://raw.githubusercontent.com/mgeekin/ieeemnnit/master/assets/
submenu: [Chapters, Workshops, Activities]

